<a href="https://colab.research.google.com/github/HSOPedro/C11B/blob/main/C11_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##NumPy

- O NumPy (Numerical Python) é uma biblioteca open source em
Python, largamente utilizada em quase todos os campos da
ciência
e engenharia

- É considerada
o núcleo
(core) dos ecossistemas PyData
(bibliotecas
e ferramentas da comunidade de Data Science em
Python)

- Outros destaques desta biblioteca
:

- Manipulação de arrays multidimentsionais como vetores
e
matrizes

- Grande variedade de operações matemáticas disponíveis
- Preparada para lidar com grandes quantidades de dados
(Sua base
é criada na linguagem C)
• Biblioteca mãe de outras, como Pandas
e MatplotLib

- O ndarray (NumPy Array) é a estrutura de dados fundamental do NumPy
- O NumPy Array guarda apenas elementos do mesmo tipo
- Isso fornece maior desempenho nas operações
- Menor uso de memória
- Aqui, utilizaremos NumPy Arrays Unidimensionais e Bidimensionais

In [ ]:
##import numpy
import numpy as np

arr = np.array([1,2,3])
print(arr)
print(type(arr))
##propriedades arry
print(arr.size)
print(arr.ndim)
print(arr.shape)



mtz = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mtz)
##propriedades arry
print(mtz.size)
print(mtz.ndim)
print(mtz.shape)



[1 2 3]
<class 'numpy.ndarray'>
3
1
(3,)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
2
(3, 3)


##funções pré prontas para estrturas de numpy aarrays

In [ ]:
## ones
mtz = np.ones([5, 5])
print(mtz)

##zeros
arr = np.zeros(10)
print(arr.reshape(5,2))


##arange

mtz = np.arange(2, 21, 2)
print(mtz.reshape(2,5))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[ 2  4  6  8 10]
 [12 14 16 18 20]]


## operações entre numpy arrays


In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr3 = arr1 + arr2
print(arr3)


print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)
print(arr1 ** arr2)

arr3 = np.concatenate([arr1, arr2])
print(arr3)

print(5*arr3)



[5 7 9]
[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]
[1 2 3 4 5 6]
[ 5 10 15 20 25 30]


In [ ]:
## estrturando uma matriz com contas

mtz= np.arange(10, 96, 5)
mtz = mtz.reshape(3,6)
print(mtz)

# extraindo a soma da primeira coluna

print(mtz.sum(axis=0)[0])

print(mtz.sum(axis=1))
print(mtz.sum(axis=1)[1])

[[10 15 20 25 30 35]
 [40 45 50 55 60 65]
 [70 75 80 85 90 95]]
120
[135 315 495]
315


## numeros aleatorios no

> Adicionar aspas



In [ ]:
arr = np.random.randint(10)
print(arr)

arr = np.random.seed(5)

arr = np.random.randint(1, 10 , 10)
print(arr)

####elementos unicos
print(np.unique(arr))

####contando elementos unicos
print(np.unique(arr, return_countsbcfet=True))

SyntaxError: incomplete input (1245714820.py, line 13)

In [ ]:
import numpy as np
np.random.seed(10)

mtz = np.random.randint(1, 99, 9).reshape(3,3)
print(mtz)

print()

print(mtz[1])

print()

print(mtz[:,2])

print()

print(mtz[1:,1:])

print()



[[10 16 65]
 [29 90 94]
 [30  9 74]]

[29 90 94]

[65 94 74]

[[90 94]
 [ 9 74]]



In [ ]:
##condicionais do  nunumpay
print(mtz)

print(mtz <70)

print(mtz[mtz<70])

print(mtz[mtz%2==0])


[[10 16 65]
 [29 90 94]
 [30  9 74]]
[[ True  True  True]
 [ True False False]
 [ True  True False]]
[10 16 65 29 30  9]
[10 16 90 94 30 74]


Analize de padroes textuais com numpy

In [ ]:
arr = np.array(['inatel', 'casa viva', 'icc', 'cdg', 'ehealth'])

print(arr)

print(np.char.find(arr,"a"))

print(np.char.find(arr,"a")>=0)

print(arr[np.char.find(arr,"a")>=0])


print('ai ai q delicidelicia ....')




['inatel' 'casa viva' 'icc' 'cdg' 'ehealth']
[ 2  1 -1 -1  3]
[ True  True False False  True]
['inatel' 'casa viva' 'ehealth']
ai ai q delicidelicia ....


## Dataset no numpy




In [ ]:
dataset = np.loadtxt('space.csv', delimiter=';', dtype= "str")
print(dataset)

[['\ufeffNum' 'Company Name' 'Location' ... 'Status Rocket' ' Cost'
  'Status Mission']
 ['0' 'SpaceX' 'LC-39A Kennedy Space Center Florida USA' ...
  'StatusActive' '50.0 ' 'Success']
 ['1' 'CASC' 'Site 9401 (SLS-2) Jiuquan Satellite Launch Center China'
  ... 'StatusActive' '29.75 ' 'Success']
 ...
 ['4321' 'US Navy' 'LC-18A Cape Canaveral AFS Florida USA' ...
  'StatusRetired' '0' 'Failure']
 ['4322' 'RVSN USSR' 'Site 1/5 Baikonur Cosmodrome Kazakhstan' ...
  'StatusRetired' '0' 'Success']
 ['4323' 'RVSN USSR' 'Site 1/5 Baikonur Cosmodrome Kazakhstan' ...
  'StatusRetired' '0' 'Success']]


In [ ]:
print(dataset[0,:])

print(dataset[1:,1])

print(np.unique(dataset[1:,1]))

printnp.unique(dataset[1:,1], return_counts=True)


['\ufeffNum' 'Company Name' 'Location' 'Datum' 'Detail' 'Status Rocket'
 ' Cost' 'Status Mission']
['SpaceX' 'CASC' 'SpaceX' ... 'US Navy' 'RVSN USSR' 'RVSN USSR']
['AEB' 'AMBA' 'ASI' 'Arianespace' "Arm??e de l'Air" 'Blue Origin' 'Boeing'
 'CASC' 'CASIC' 'CECLES' 'CNES' 'Douglas' 'EER' 'ESA' 'Eurockot' 'ExPace'
 'Exos' 'General Dynamics' 'IAI' 'ILS' 'IRGC' 'ISA' 'ISAS' 'ISRO' 'JAXA'
 'KARI' 'KCST' 'Khrunichev' 'Kosmotras' 'Land Launch' 'Landspace'
 'Lockheed' 'MHI' 'MITT' 'Martin Marietta' 'NASA' 'Northrop' 'OKB-586'
 'OneSpace' 'RAE' 'RVSN USSR' 'Rocket Lab' 'Roscosmos' 'SRC' 'Sandia'
 'Sea Launch' 'SpaceX' 'Starsem' 'ULA' 'US Air Force' 'US Navy' 'UT'
 'VKS RF' 'Virgin Orbit' 'Yuzhmash' 'i-Space']
