<a href="https://colab.research.google.com/github/HSOPedro/C11B/blob/main/Lista_exercicio_cap4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Crie dois NumPy Arrays unidimensionais de tamanho
8
: um formado apenas
por
1’s
e outro formado por números aleatórios entre
0
e
9
. Some estes dois
NumPy Arrays
e guarde
o resultado dentro de um terceiro NumPy Array. Por
fim, faça
o seguinte
:
- a. Se
a soma de todos os elementos do Array resultante for >= 40
, remodele este
NumPy Array para se tornar uma matriz com mais linhas do que colunas
. Senão,
remodele para que se torne uma matriz com mais colunas do que linhas
.

In [ ]:
import numpy as np

arr = np.ones(8)

arr_rand = np.random.randint(0, 10, 8)

arr_sum = arr + arr_rand

if np.sum(arr_sum) >= 40:
    mtz = arr_sum.reshape(4,2)
elif np.sum(arr_sum) < 40:
    arr_sum.reshape(2,4)
    mtz = arr_sum.reshape(2,4)
print(mtz)

[[ 5.  8.]
 [10.  5.]
 [ 4.  8.]
 [ 1.  5.]]


2
. Crie dois NumPy Arrays unidimensionais
: um de números pares de
0
à 51
e
outro também de números pares de 100 até 50
. Em seguida, os concatene
e
mostre os resultados ordenados



In [ ]:
import numpy as np

arr1 = np.arange(0, 52, 2)
arr2 = np.arange(100, 51, -2)

print(arr1)
print("    ")
print(arr2)

concatene_arr = np.concatenate((arr1, arr2))

ordem_arr = np.sort(concatene_arr)

print("    ")
print(ordem_arr)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50]
    
[100  98  96  94  92  90  88  86  84  82  80  78  76  74  72  70  68  66
  64  62  60  58  56  54  52]
    
[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


3. Mini Campo Minado
- a) Crie um NumPy Array
2
x
2 formado apenas por
0’s
- b) Em seguida, adicione um número
1 em uma posição aleatória desta matriz
;
- c) Faça uma entrada de dados para solicitar
o usuário que faça uma jogada
(selecione uma posição da matriz)
- I. Se ele selecionar todas as posições em que
o número
1 não se encontra, mostre
a
mensagem
“Congratulations
! You beat the game!
:
)
”
- II. Senão, se dentro das
3 primeiras jogadas ele achar
o número
1
, mostre
a mensagem
“Game Over!
:
( Try Again!
”

In [32]:
import numpy as np

mtz = np.zeros((2,2))

linha = np.random.randint(0, 2)
coluna = np.random.randint(0, 2)

mtz[linha, coluna] = 1

print(f"A bomba está em: ({linha}, {coluna})")

print(mtz)

cont = 0

for i in range(3):
  linha = int(input("\nDigite a linha (0 ou 1): "))
  coluna = int(input("Digite a coluna (0 ou 1): "))

  if mtz[linha, coluna] == 1:
    print("\nGame Over!:( Try Again!)")
    break
  elif mtz[linha, coluna] != 1:
    print("\nPróxima jogada!")
    cont+=1

if cont == 3:
  print("\nCongratulations! You beat the game!:)")

A bomba está em: (0, 1)
[[0. 1.]
 [0. 0.]]

Digite a linha (0 ou 1): 0
Digite a coluna (0 ou 1): 0

Próxima jogada!

Digite a linha (0 ou 1): 0
Digite a coluna (0 ou 1): 1

Game Over!:( Try Again!)


4 - Crie uma matriz de tamanho qualquer. Extraia seu número de linhas e colunas, multiplique-os, e diga se esta matriz poderia se tornar um vetor unidimensional com número par ou ímpar de elementos

In [ ]:
import numpy as np

linha = np.random.randint(0, 6)
coluna = np.random.randint(0, 6)

arr = np.random.randint(1, 51, linha*coluna)

mtz = arr.reshape(linha, coluna)

print(mtz)

[[26 14 29 23 31]
 [31 26 13  2 32]
 [37 28 19 30 14]
 [23 24 31 12 29]
 [11 25 10 16 19]]

quant_col = mtz.shape[1]
quant_lin = mtz.shape[0]

print("número de colunas: ", quant_col)
print("número de linhas: ", quant_lin)
print("número de elementos: ", quant_col*quant_lin)

if quant_col*quant_lin % 2 == 0:
  print("\nPode virar vetor com numero par elementos")
else:
  print("\nPode virar vetor com numero ímpar de elementos")

5 - Crie uma matriz de tamanho 4x4 formada por números aleatórios inteiros entre 1 e 50 (use seed = 10 antes)
- Mostre o resultado da média de cada linha e cada coluna da matriz gerada

- Apresente o maior valor das médias das linhas e também das colunas

- Mostre a quantidade de aparições de cada um dos números gerados na matriz. Em seguida, mostre apenas os números que aparecem 2 vezes

In [ ]:
import  numpy as np

np.random.seed(10)#organiza a seed

arr = np.random.randint(1, 51, 16)
mtz = arr.reshape(4, 4)

print(mtz)

print("\nMedia de cada linha: ")
print(mtz.sum(axis=1)/4)
print("Maior valor: ")
print((mtz.sum(axis=1)/4).max())

print("\nMedia de cada coluna: ")
print(mtz.sum(axis=0)/4)
print("Maior valor: ")
print((mtz.sum(axis=0)/4).max())

print("\nQuantidade de aparições de cada numero: ")
aparicoes = np.unique(mtz, return_counts = True)
print(aparicoes)

print("\nAparecem 2 vezes: ")
for i in range(len(np.unique(mtz))):
  if aparicoes[1][i] == 2:
    print(aparicoes[0][i])
